
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'DIRECTORY LS OPTION OPTION_LONGstatement : ls option directoryls : LSoption : OPTION\n    | OPTION_LONG\n    | emptydirectory : DIRECTORYempty :'
    
_lr_action_items = {'LS':([0,],[3,]),'$end':([1,8,9,],[0,-1,-6,]),'OPTION':([2,3,],[5,-2,]),'OPTION_LONG':([2,3,],[6,-2,]),'DIRECTORY':([2,3,4,5,6,7,],[-7,-2,9,-3,-4,-5,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement':([0,],[1,]),'ls':([0,],[2,]),'option':([2,],[4,]),'empty':([2,],[7,]),'directory':([4,],[8,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> ls option directory','statement',3,'p_statement','lsparse.py',11),
  ('ls -> LS','ls',1,'p_ls','lsparse.py',17),
  ('option -> OPTION','option',1,'p_option','lsparse.py',22),
  ('option -> OPTION_LONG','option',1,'p_option','lsparse.py',23),
  ('option -> empty','option',1,'p_option','lsparse.py',24),
  ('directory -> DIRECTORY','directory',1,'p_directory','lsparse.py',29),
  ('empty -> <empty>','empty',0,'p_empty','lsparse.py',34),
]
