
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = b'\xd3)\x88V\xf2\xae\xd7\xf0\x10\x80\xf7D\x05\x0e\x13\x15'
    
_lr_action_items = {'LS':([0,],[3,]),'$end':([1,4,5,6,7,8,9,],[0,-7,-3,-4,-1,-5,-6,]),'OPTION':([2,3,],[5,-2,]),'OPTION_LONG':([2,3,],[6,-2,]),'DIRECTORY':([4,5,6,],[8,-3,-4,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement':([0,],[1,]),'ls':([0,],[2,]),'option':([2,],[4,]),'directory':([4,],[7,]),'empty':([4,],[9,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> ls option directory','statement',3,'p_statement','c:\\Users\\anju5\\beech\\lsparse.py',6),
  ('ls -> LS','ls',1,'p_ls','c:\\Users\\anju5\\beech\\lsparse.py',12),
  ('option -> OPTION','option',1,'p_option','c:\\Users\\anju5\\beech\\lsparse.py',17),
  ('option -> OPTION_LONG','option',1,'p_option','c:\\Users\\anju5\\beech\\lsparse.py',18),
  ('directory -> DIRECTORY','directory',1,'p_directory','c:\\Users\\anju5\\beech\\lsparse.py',23),
  ('directory -> empty','directory',1,'p_directory','c:\\Users\\anju5\\beech\\lsparse.py',24),
  ('empty -> <empty>','empty',0,'p_empty','c:\\Users\\anju5\\beech\\lsparse.py',29),
]
